name: Hound
version: 0.3.0
main: Hound
api-version: 1.16
authors: [ Midnightfury, vinhowe ]
description: Find chests
permissions:
  hound.*:
    default: op
    description: Give players with op everything by default

