name: Hound
version: 0.3.0
main: Hound
api-version: 1.16
authors: [ Midnightfury, vinhowe ]
description: Find chests
commands:
  lchound:
    usage: /<command> [on|off]
    description: Live search mode. While active, highlights item held in main hand in nearby containers.
    aliases: [ lcf ]
    permission: hound.search.container.live
  target:
    usage: /<command> <x> <z>
    description: Create a floating guide that will lead you to coordinates.
    aliases: [ x ]
    permission: hound.target
  torchguide:
    usage: /<command> <x> <z>
    description: Highlight a grid guide for torches
    aliases: [ tg ]
    permission: hound.torchguide
permissions:
  hound.*:
    default: op
    description: Give players with op everything by default

