name: Hound
version: 0.1.0
main: Hound
api-version: 1.16
authors: [ Midnightfury, vinhowe ]
description: Find chests
depend:
  - ProtocolLib
commands:
  hound:
    usage: /<command> <item>
    description: locate an item in a chest
    aliases: [ cf, search]
permissions:
  hound.*:
    default: op
    description: Give players with op everything by default