name: Hound
version: 0.2.0
main: Hound
api-version: 1.16
authors: [ Midnightfury, vinhowe ]
description: Find chests
depend:
  - ProtocolLib
commands:
  hound:
    usage: /<command> <item>
    description: Highlight item in nearby containers.
    aliases: [ cf, search ]
  lhound:
    usage: /<command> [on|off]
    description: Live search mode. While active, highlights item held in main hand in nearby containers.
    aliases: [ lcf, lsearch ]
permissions:
  hound.*:
    default: op
    description: Give players with op everything by default